# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zmarth <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/24 20:40:46 by zmarth            #+#    #+#              #
#    Updated: 2020/08/24 20:46:33 by zmarth           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file
SRCS=srcs/*.c

all:
		gcc $(SRCS) -o $(NAME)

clean:
		/bin/rm -f *.o

fclean:	clean
		/bin/rm -f $(NAME)

re:	fclean re
